<?php

use App\Models\Estate;
use App\Models\EstateSubscription;
use App\Models\Invoice;
use App\Models\Plan;
use App\Models\ResidentSubscription;
use App\Models\User;
use App\Notifications\Resident\InvoicePaidNotification;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Notification;

uses(RefreshDatabase::class);

beforeEach(function () {
    Config::set('paystack.secret_key', 'test_secret_key');
});

test('it processes a successful resident payment webhook', function () {
    // 1. Setup data
    $estate = Estate::factory()->create();
    $user = User::factory()->create();
    $plan = Plan::factory()->create(['price' => 500000]); // 5000 Naira

    // Create Estate Subscription to provide the billing interval
    EstateSubscription::factory()->create([
        'estate_id' => $estate->id,
        'plan_id' => $plan->id,
        'billing_interval' => 'annually',
        'status' => 'active',
    ]);

    $residentSubscription = ResidentSubscription::factory()->create([
        'user_id' => $user->id,
        'estate_id' => $estate->id,
        'status' => 'past_due',
        'current_period_end' => now()->subDay(),
    ]);

    $invoice = Invoice::factory()->create([
        'user_id' => $user->id,
        'estate_id' => $estate->id,
        'plan_id' => $plan->id,
        'invoice_number' => 'KTRL-TEST-123',
        'amount' => 500000,
        'status' => 'pending',
    ]);

    // 2. Prepare Fake Paystack Payload
    $payload = [
        'event' => 'charge.success',
        'data' => [
            'id' => 12345,
            'domain' => 'test',
            'status' => 'success',
            'reference' => 'KTRL-TEST-123',
            'amount' => 500000,
            'channel' => 'card',
            'customer' => [
                'email' => $user->email,
            ],
            'authorization' => [
                'authorization_code' => 'AUTH_test_code',
                'brand' => 'visa',
                'last4' => '4444',
            ],
        ],
    ];

    $jsonPayload = json_encode($payload);
    $signature = hash_hmac('sha512', $jsonPayload, 'test_secret_key');

    // 3. Send Webhook Request with raw body to ensure signature matches
    Notification::fake();

    $response = $this->call(
        'POST',
        '/webhooks/paystack',
        [],
        [],
        [],
        [
            'HTTP_X_PAYSTACK_SIGNATURE' => $signature,
            'CONTENT_TYPE' => 'application/json',
        ],
        $jsonPayload
    );

    // 4. Assertions
    $response->assertStatus(200);

    $invoice->refresh();
    expect($invoice->status)->toBe('paid');
    expect($invoice->paid_at)->not->toBeNull();

    $residentSubscription->refresh();
    expect($residentSubscription->status)->toBe('active');
    expect($residentSubscription->current_period_start)->not->toBeNull();

    // Verify Notification was sent
    Notification::assertSentTo($user, InvoicePaidNotification::class, function ($notification) use ($invoice) {
        return $notification->invoice->id === $invoice->id;
    });
});

test('it handles auto-billing references correctly', function () {
    // 1. Setup
    $estate = Estate::factory()->create();
    $user = User::factory()->create();
    $plan = Plan::factory()->create(['price' => 500000]);

    EstateSubscription::factory()->create([
        'estate_id' => $estate->id,
        'plan_id' => $plan->id,
        'billing_interval' => 'annually',
    ]);

    $invoice = Invoice::factory()->create([
        'user_id' => $user->id,
        'estate_id' => $estate->id,
        'invoice_number' => 'KTRL-AUTO-123',
        'status' => 'pending',
    ]);

    // Reference with the -AUTO- suffix as generated by our background job
    $autoReference = 'KTRL-AUTO-123-AUTO-'.now()->format('Y-m-d');

    $payload = [
        'event' => 'charge.success',
        'data' => [
            'status' => 'success',
            'reference' => $autoReference,
            'amount' => 500000,
            'customer' => ['email' => $user->email],
        ],
    ];

    $jsonPayload = json_encode($payload);
    $signature = hash_hmac('sha512', $jsonPayload, 'test_secret_key');

    // 2. Act
    $response = $this->call(
        'POST',
        '/webhooks/paystack',
        [],
        [],
        [],
        [
            'HTTP_X_PAYSTACK_SIGNATURE' => $signature,
            'CONTENT_TYPE' => 'application/json',
        ],
        $jsonPayload
    );

    // 3. Assert
    $response->assertStatus(200);
    $invoice->refresh();
    expect($invoice->status)->toBe('paid');
});
